### PR TITLE
Add events handling

### PR DESCRIPTION
**Pull request by symbx**
Package miss plotly event handling trough vue.
Code ported from vue2-plotly

### CODE REVIEW

**Comment by niZaliznyak** [comment]
Hello, @Pietervanhalem)
I really need this feature, cause now I'm work on migrating my project from vue 2 to vue 3. And I need internal emitted events 🙏.
Approve PR pls)

**Comment by LittleLama** [comment]
Proposed too in https://github.com/VanOord/vue3-plotly/pull/10

**Review by Pietervanhalem — APPROVED** [review]
Thanks for your contribution! lets merge and I will release it under v0.0.8

**Comment by rjruizes** [comment]
@Pietervanhalem Would really appreciate if this could be released. Thanks!

**Pull request closed without merging**
